### ISSUE TITLE
Bundling a static page with the extension

### ISSUE THREAD

**Issue by guytepper** [samrum/vite-plugin-web-extension#3]
Hey there!
Big thanks for this template. I've been on the hunt for one for a while, and this is the best one I found!

I have a question regarding bundling a static page with the extension:
On my background page I want to redirect the user to a static page that will come bundled with the extension. I've been trying to figure how to configure Vite to bundle the page alongside the manifest entry files, but couldn't figure it out. 
Any clues on how make it happen?

The static page will use svelte, if it matters 🤓

**Comment by samrum** [comment]
Hey, awesome that you found it useful!

You should be able to add the html file you want to be bundled to the web_accessible_resources key of your manifest definition and the plugin will process it like the other manifest html files. 

It’s intentional that background scripts get wrapped in an html page. It’s so that the script can be loaded as an ES module since manifest scripts can’t be loaded directly as modules.

**Comment by guytepper** [comment]
Thanks for the explanations! It worked :)
